import { gzipSync } from 'node:zlib';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const dist = resolve(root, 'build/web');
let html = await readFile(resolve(dist, 'index.html'), 'utf8');
const css = await readFile(resolve(dist, 'app.css'), 'utf8');
const javascript = await readFile(resolve(dist, 'app.js'), 'utf8');
// Vite minifies scripts and styles but preserves template indentation. Remove
// whitespace between HTML tags before embedding to protect the flash budget.
html = html.replace(/>\s+</g, '><').trim()
  // Vite may reorder attributes between versions, so match the fixed asset name
  // instead of depending on a particular serialization of the element.
  .replace(/<link[^>]*app\.css[^>]*>/, () => `<style>${css}</style>`)
  .replace(/<script[^>]*app\.js[^>]*>/, () => `<script type="module">${javascript}`);
const remainingAssetTag = html.match(/<(?:link|script)[^>]*(?:app\.css|app\.js)[^>]*>/)?.[0];
if (remainingAssetTag) {
  throw new Error(`Vite asset inlining failed: ${remainingAssetTag}`);
}
const compressed = gzipSync(Buffer.from(html), { level: 9, mtime: 0 });
await writeFile(resolve(dist, 'index.html.gz'), compressed);
const rows = [];
for (let i = 0; i < compressed.length; i += 12) {
  rows.push('    ' + [...compressed.subarray(i, i + 12)].map(value => `0x${value.toString(16).padStart(2, '0')}`).join(', '));
}
const header = `#pragma once

// Generated by tools/embed-web.mjs from the minified Vite build.
// Do not edit this byte array by hand.
static const uint8_t WEB_INDEX_GZIP[] PROGMEM = {
${rows.join(',\n')}
};
static const size_t WEB_INDEX_GZIP_LENGTH = sizeof(WEB_INDEX_GZIP);
`;
await writeFile(resolve(root, 'firmware/AdvatekTrigger/src/web/WebAsset.h'), header);
console.log(`Embedded ${html.length} bytes of HTML as ${compressed.length} gzipped bytes.`);
